// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

type AggregatedPrice struct {
	ID       int64
	Currency string
	Value    int64
	MinuteTs int64
}

type ExchangePrice struct {
	ID       int64
	Exchange string
	Currency string
	Value    int64
	MinuteTs int64
}
