// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package sqlc

import (
	"context"
)

const aggregatedPriceAt = `-- name: AggregatedPriceAt :one
SELECT id, currency, value, minute_ts
FROM aggregated_prices
WHERE currency = ? AND minute_ts <= ?
ORDER BY minute_ts DESC
LIMIT 1
`

type AggregatedPriceAtParams struct {
	Currency string
	MinuteTs int64
}

func (q *Queries) AggregatedPriceAt(ctx context.Context, arg AggregatedPriceAtParams) (AggregatedPrice, error) {
	row := q.db.QueryRowContext(ctx, aggregatedPriceAt, arg.Currency, arg.MinuteTs)
	var i AggregatedPrice
	err := row.Scan(
		&i.ID,
		&i.Currency,
		&i.Value,
		&i.MinuteTs,
	)
	return i, err
}

const exchangePriceAt = `-- name: ExchangePriceAt :one
SELECT id, exchange, currency, value, minute_ts
FROM exchange_prices
WHERE currency = ? AND exchange = ? AND minute_ts = ?
`

type ExchangePriceAtParams struct {
	Currency string
	Exchange string
	MinuteTs int64
}

func (q *Queries) ExchangePriceAt(ctx context.Context, arg ExchangePriceAtParams) (ExchangePrice, error) {
	row := q.db.QueryRowContext(ctx, exchangePriceAt, arg.Currency, arg.Exchange, arg.MinuteTs)
	var i ExchangePrice
	err := row.Scan(
		&i.ID,
		&i.Exchange,
		&i.Currency,
		&i.Value,
		&i.MinuteTs,
	)
	return i, err
}

const insertAggregatedPrice = `-- name: InsertAggregatedPrice :exec
INSERT INTO aggregated_prices (currency, value, minute_ts)
VALUES (?, ?, ?)
ON CONFLICT(currency, minute_ts) DO UPDATE SET value = excluded.value
`

type InsertAggregatedPriceParams struct {
	Currency string
	Value    int64
	MinuteTs int64
}

func (q *Queries) InsertAggregatedPrice(ctx context.Context, arg InsertAggregatedPriceParams) error {
	_, err := q.db.ExecContext(ctx, insertAggregatedPrice, arg.Currency, arg.Value, arg.MinuteTs)
	return err
}

const insertExchangePrice = `-- name: InsertExchangePrice :exec
INSERT INTO exchange_prices (exchange, currency, value, minute_ts)
VALUES (?, ?, ?, ?)
ON CONFLICT(exchange, currency, minute_ts) DO UPDATE SET value = excluded.value
`

type InsertExchangePriceParams struct {
	Exchange string
	Currency string
	Value    int64
	MinuteTs int64
}

func (q *Queries) InsertExchangePrice(ctx context.Context, arg InsertExchangePriceParams) error {
	_, err := q.db.ExecContext(ctx, insertExchangePrice,
		arg.Exchange,
		arg.Currency,
		arg.Value,
		arg.MinuteTs,
	)
	return err
}

const latestAggregatedPrice = `-- name: LatestAggregatedPrice :one
SELECT id, currency, value, minute_ts
FROM aggregated_prices
WHERE currency = ?
ORDER BY minute_ts DESC
LIMIT 1
`

func (q *Queries) LatestAggregatedPrice(ctx context.Context, currency string) (AggregatedPrice, error) {
	row := q.db.QueryRowContext(ctx, latestAggregatedPrice, currency)
	var i AggregatedPrice
	err := row.Scan(
		&i.ID,
		&i.Currency,
		&i.Value,
		&i.MinuteTs,
	)
	return i, err
}

const listAggregatedPrices = `-- name: ListAggregatedPrices :many
SELECT id, currency, value, minute_ts
FROM aggregated_prices
WHERE currency = ? AND minute_ts >= ? AND minute_ts <= ?
ORDER BY minute_ts ASC
`

type ListAggregatedPricesParams struct {
	Currency   string
	MinuteTs   int64
	MinuteTs_2 int64
}

func (q *Queries) ListAggregatedPrices(ctx context.Context, arg ListAggregatedPricesParams) ([]AggregatedPrice, error) {
	rows, err := q.db.QueryContext(ctx, listAggregatedPrices, arg.Currency, arg.MinuteTs, arg.MinuteTs_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AggregatedPrice
	for rows.Next() {
		var i AggregatedPrice
		if err := rows.Scan(
			&i.ID,
			&i.Currency,
			&i.Value,
			&i.MinuteTs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
